Add conv sw test
KULeuven-MICAS/snax_cluster pull request #144
Opened 2024-06-04 13:16 UTC by xiaoling-yi

2024-06-05 14:24 UTC, rgantonio approved these changes
Good job!!! ❤️ ❤️ ❤️ ❤️ ❤️

2024-06-06 09:40 UTC, JosseVanDelm requested changes
This looks like a very good PR! However, I really would need some extra help understanding what is going on and I think this PR requires a lot more documentation. I also don't have a lot of time to check it in this much detail, but I still think some important bits are missing that we would need.
Some things are general comments (can be solved in later PRs) other things are quite important to get right ASAP (this PR hopefully?)

* For a 1,152 PR the explanation is not that detailed. Can you please add a bit more context in the PR description? (This PR!)
* There is not a lot documentation going when it comes to data layout. Conv2D is very elaborate in its possiblities, NHWC, NCHW, NCHWc...
What did you pick here and why? (This PR, current assumption/initial thought is fine, please just document the currently assumed data layouts)
* Can you please do a really good effort in documenting what each of these parameters need to be set to. I'd rather have too much docs/comments here than too few.
There are many parameters to set here, and it takes just one to be misconfigured to lead to very long and annoying debugging in the end. (This PR please please please)
* Can you please document all the constraints this conv2d unit has? Does it support all kinds of strides, pads, or do left and right padding always need to be the same maybe? (Current assumptions and limitiations in this PR please!)
* While it is great that you are testing (Really ! Thanks!) You are testing this entire unit with just one set of parameters? How can we ever know it will not trigger some weird behaviour in some corner case? (Not this PR? Not sure?)
* What is an implicit im2col?
* General comment: I have the impression that a lot of this code is copy pasted and that this leads to a lot of code duplication. If we are copy pasting a lot that should ring some alarm bell, can we think of ways to add accelerators to this in less than 1152 lines?  (Not this PR?)

2024-06-06 09:40 UTC, JosseVanDelm commented on target/snitch_cluster/cfg/snax-streamer-gemm-conv.hjson
> +// Cluster configuration for a simple testbench system.
This is not a simple testbench system, is it?

2024-06-06 09:40 UTC, JosseVanDelm commented on target/snitch_cluster/cfg/snax-streamer-gemm-conv.hjson
> +    },
This template is not used

2024-06-06 09:40 UTC, JosseVanDelm commented on target/snitch_cluster/sw/snax/streamer-gemm-conv/src/snax-streamer-gemm-conv-lib.c
> +// Poll until Streamer and GEMM accelerator finish
Are these polling though?
```suggestion
// Stall until Streamer and GEMM accelerator finish
```

2024-06-06 09:40 UTC, JosseVanDelm commented on target/snitch_cluster/sw/apps/snax-streamer-gemm-conv/data/datagen.py
> +    # 1, 8 * N, im2col_conv2d_res, 1)
Why is this commented out?

2024-06-06 09:40 UTC, JosseVanDelm commented on target/snitch_cluster/sw/apps/snax-streamer-gemm-conv/data/datagen.py
> +    # data_str += [format_vector_definition("int8_t", "B", im2col_kernel)]
Why is this commented out?

2024-06-06 09:40 UTC, JosseVanDelm commented on target/snitch_cluster/sw/apps/snax-streamer-gemm-conv/data/datagen.py
> +def test():
What is this test for?

2024-06-06 09:40 UTC, JosseVanDelm commented on target/snitch_cluster/sw/apps/snax-streamer-gemm-conv/data/datagen.py
> +    return result_array.ravel()
Is this not tested elsewhere, and can we thus not get that function from somewhere else?

2024-06-06 11:06 UTC, JosseVanDelm commented
Okay for me to put this PR through and delay the docs for later, but please do address some of the minor comments @xiaoling-yi

2024-06-06 11:06 UTC, JosseVanDelm approved these changes
Please still have a look at some of the suggestions! Thanks for this work @xiaoling-yi !

2024-06-06 12:26 UTC, xiaoling-yi commented
Hi @JosseVanDelm thanks for your comments! I address some! The repeated golden model codes will be put in a python util in later PR when I have more time! I will add the doc later after the tight tape out ddl..
Let's leave the comments for future reference!

2024-06-06 12:52 UTC, merged