Add gemm and simd src code
KULeuven-MICAS/snax_cluster pull request #157
Opened 2024-06-14 11:59 UTC by xiaoling-yi

We migrated the chisel code in the separate repos in this PR.
The test for these two accelerators will be added later, including
* sw test in C (next PR)
* scala test (in the longer term)

`chisel_acc` is a temporal name. Please let me know if there is a better name.

2024-06-14 12:17 UTC, rgantonio approved these changes
OK!

2024-06-14 12:38 UTC, jorendumoulin requested changes
Wait, we cannot just copy and paste the code from gemm right?

The code should not live in two places at the same time, either we move it here, or only the external repository. Otherwise we return to the problem if one thing needs to change we need to change it in two spots!

If you need help on how to make this happen with mill or sbt, let me know!

2024-06-14 12:42 UTC, xiaoling-yi commented
Hi @jorendumoulin 

> Wait, we cannot just copy and paste the code from gemm right?

It is not a just copy and paste. I updated the gemm a bit.

> The code should not live in two places at the same time, either we move it here, or only the external repository. Otherwise we return to the problem if one thing needs to change we need to change it in two spots!

Yes, we will remove the old gemm repo from snax_cluster  in the next pr.
> 
> If you need help on how to make this happen with mill or sbt, let me know!

What do you mean make this happen with mill or sbt,? :)

2024-06-14 13:17 UTC, jorendumoulin reviewed
Ok, if the other repostories close, i am very happy 😄 

However, the different accelerators are maybe not super well separated like this. Is the following possible? What do you think about this?
```
/
└── hw
    └── accelerators
        ├── gemm
        │   ├── src/main/scala
        │   │   └── gemm_scala_source.scala
        │   └── wrapper.sv
        ├── simd
        │   ├── src/main/scala
        │   │   └── simd_scala_source.scala
        │   └── wrapper.sv
        ├── gemm-simd
        │   ├── src/main/scala
        │   │   └── gemm-simd_scala_source.scala
        │   └── wrapper.sv
        ├── build.sbt
        └── Makefile
```

2024-06-14 13:17 UTC, jorendumoulin commented on hw/chisel_acc/build.sbt
> +    name := "chisel-gemm",
```suggestion
    name := "snax-accelerators",
```

2024-06-14 14:19 UTC, jorendumoulin commented
Could you maybe just take a look at this if it is possible like this?
https://github.com/jackkoenig/mill-multi-project

Or for sbt  (seems more difficult)
https://www.scala-sbt.org/1.x/docs/Multi-Project.htm

2024-06-17 08:23 UTC, xiaoling-yi commented
> Could you maybe just take a look at this if it is possible like this? (Jack Koenig is the lead developer of chisel, so he must know what he's doing 😆 ) https://github.com/jackkoenig/mill-multi-project
> 
> Or for sbt (seems more difficult) https://www.scala-sbt.org/1.x/docs/Multi-Project.html

Nice finding! It seems doable to manage several projects and share the code between them. But we can also view the accelerators as one big Scala project? In that sense, is it ok to maintain the file structure as we have now?

How about leaving this file structure for now but if we indeed need improvement then we discuss it later?

2024-06-17 08:35 UTC, jorendumoulin approved these changes
Ok!
Are you ok if I try to fix this later?

2024-06-17 08:43 UTC, xiaoling-yi commented
Hi, wait, not yet! Actually, the goal I put it together is to make the gemm and rescaling simd together. We would like to view it as a big accelerator because they are so interdependent.

I just realized later they need to be combined that is why I want them together.

It just so happens we can also separate them but it makes much more sense that they are combined to reduce having to load/store into memory many times! 

It's funny because the latest reviewer from the MICRO paper also said to combine them together!

2024-06-17 08:58 UTC, JosseVanDelm commented
Hi, 

I like this PR, because now it seems we are going for a more monolithic repo after all :D 
I think doing a multi-project build for each and every accelerator is a bit against the purpose of going monolithic, so I'm not sure I agree with @jorendumoulin? For sure we would need it later if people want to include their own accelerator as an external dependency.
Note that we are already shipping two distinct packages inside this repo (the accelerators and the streamers) and if we'd like to keep them seperate (should we really though?), a correct setup for a multi-project build might be beneficial here after all.? 

I don't like
> I updated the gemm and cleaned a bit. :)

Can you make an overview of what you changed (just for us for future reference!)? We can not see the diff here, because all these files are new changes in this repository! Without knowing what you did, I think It would have been better if you did the changes there first and later migrated them here? 

Is there any reason why we are still using sbt and mill together? Can we not just move to a single build system?

@xiaoling-yi there is no CI change in this PR. Since you are adding sbt build files it seems like you are doing a local build anyway. I think it still makes sense to add a simple scala build here, even if it is to change it in the next pr. You never know what is setup wrong; the devil is in the details here.

Overall this is a really nice progression in my opinion.

2024-06-17 09:27 UTC, merged