csr soft_switch function in snrt.h
KULeuven-MICAS/snax_cluster pull request #202
Opened 2024-07-24 12:25 UTC by IveanEx

This PR provides the function to read and write CSR with CSR address in register
As CSR instruction in RISC-V is immediate-number addressed, this workaround function deploys a switch-case to map the CSR address to implement pseudo register-mapping mechanism. To avoid the loss of performance, the function is defined in header, so that it can be compiled together with the main program and optimized by the compiler. If @csr_address is provided in an immediate number, (macros, constant etc.) no clock cycles will be wasted on the switch-case.

2024-07-24 13:00 UTC, rgantonio reviewed
I am okay with this!

Just an FYI @jorendumoulin  and @JosseVanDelm, do you remember the problem with CSR instructions where we cannot dynamically set the values to be written unto it? AKA we are required to explicitly write the register addresses like:

```c
csr_write(960, value_a);
csr_write(961, value_b);
```

This workaround fixes it. @IveanEx found an interesting solution to it. Instead, we can write any value into the CSR register address argument, you can also use macros from header files. This is more elegant as the naming is more consistent! So it becomes:

```c
write_csr_soft_switch(STREAMER_STRIDE_1, value_a);
write_csr_soft_switch(STREAMER_STRIDE_2, value_b);
```

The limitation is due to the RISCV compiler does not want us to use the macros or variables but requires us to use the actual value. @IveanEx is free to discuss or explain better! It's a cool work around really.

2024-07-25 09:02 UTC, JosseVanDelm requested changes
Hi, I don't fully agree with this being a good workaround.
* It arbitrarily puts a constraint on the amount of CSRs this function can use (I believe at some point this will confuse a lot of people). Now people have to decide upfront how much CSRs they can use before they use this system. Before they were only limited by the amount of CSRs in the RISC-V spec.
* What is the use case for setting this value dynamically @rgantonio ? The compiler can not optimize away this entire routine if the value is not known at compile time, as such it will create a giant jump routine with a lot of runtime overhead? If at some point we need this let's not implement it as a jump routine to all possible registers, but only to the 3 or 5 registers that at that point make sense to switch between?
* If it is to make the naming of the registers more clear (the use of constants), i'd much rather use what they do over at gemmini; we just define a different macro that sets the registers so instead of:
```c
write_csr_soft_switch(STREAMER_STRIDE_1, value_a);
write_csr_soft_switch(STREAMER_STRIDE_2, value_b);
```
Just define a new macro that calls the `write_csr` macro:
```c
SET_STREAMER_STRIDE_1(value_a);
SET_STREAMER_STRIDE_2(value_b);
```
It will take an equal amount of lines to add this macro than it will to add a line like:
```c
#define STREAMER_STRIDE_1 960
```
* Most of this setup will be simplified by the use of the compiler anyway, so too much development on syntactic sugar here is a bit of waste of time in my opinion

2024-07-25 09:27 UTC, IveanEx commented
Hi Josse, 

This workaround is designed to be used internally in my xdma, to do the addressing with dynamic address and macro-defined address. For me, it is also confusing for me to define "write_csr" or "read_csr" macro like a function, while it cannot be operated like a real function. So, this workaround aims to make it like a real function, in which the argument can be passed whatever way you like, with the maximum preservation of performance. 

This function will be useful for people that write C code directly, and the people that use our framework.

2024-07-25 09:39 UTC, rgantonio commented on sw/snRuntime/src/csr.h
> +            return read_csr(960);
I'll answer this. When we first started the SNAX to use CSR, this was one of the currently available spaces in the Snitch (around June last year we figured this out).

I manually traced it from the definitions in [`riscv_inst.sv`](https://github.com/KULeuven-MICAS/snax_cluster/blob/main/hw/snitch/src/riscv_instr.sv) (scroll down at the bottom)

Made a mapping [here](https://danknight.notion.site/Snitch-CSR-Study-348e1497cbb448f7bde4d0f1600769e0?pvs=4).

2024-07-25 09:40 UTC, rgantonio commented on sw/snRuntime/src/csr.h
> +// of larger binary size.
We can extend it anyway. So far we aren't setting more than 64. I mean it's just adding more cases...

2024-07-25 09:46 UTC, rgantonio commented
> We just define a different macro that sets the registers so instead of ...

I think it's a good point too. So the choice is either:

1. @IveanEx - style where we have a general set CSR function (just like csr_write and csr_read) but we have the register addresses as macros:

```c
write_csr_soft_switch(STREAMER_STRIDE_1, value_a);
write_csr_soft_switch(STREAMER_STRIDE_2, value_b);
```

2. @JosseVanDelm  - style (or gemmini style?) where the MACROs are directly the functions themselves.

```c
SET_STREAMER_STRIDE_1(value_a);
SET_STREAMER_STRIDE_2(value_b);
```

@IveanEx could you brain storm and see if @JosseVanDelm's suggestion is better? Also, I don't think it's a waste of time. I mean the problem we had before was to solve the ever-growing number of registers from @xiaoling-yi 's examples and we just always write `csr_write(<insert number here>, <insert_value here>)` but the numbers don't make sense. I thought our goal before was to make coding *idiomatic* such hat it's understandable right?

2024-07-25 11:22 UTC, JosseVanDelm commented
> I don't think it's a waste of time.
> This function will be useful for people that write C code directly, and the people that use our framework.

Apologies! Maybe I'm phrasing that too strongly.

> this workaround aims to make it like a real function, in which the argument can be passed whatever way you like, with the maximum preservation of performance.

I think the main reason people use macros for this, is because real functions can come with quite some overhead if you are not careful with your implementation.

> This workaround is designed to be used internally in my xdma, to do the addressing with dynamic address and macro-defined address.

I can understand why you prefer a macro-defined address, but I don't like the enormous switch statement. the alternative I am proposing gives you a very similar benefit to the macro's without any switch statement.
I don't understand however, why we would need to dynamically offset the address?

2024-07-25 11:28 UTC, rgantonio commented
> I don't understand however, why we would need to dynamically offset the address?

Aha! I see the confusion, I think the "dynamically offsetting the address" is the wrong example haha. 
I think you phrased it better with the "macro-defined addressing".

Because the current `csr_write` and `csr_read` does not like the:

```c
csr_write(STREAMER_STRIDE_1, value_a);
csr_write(STREAMER_STRIDE_2, value_b);
```

It requires that we write explicitly the values like `csr_write(960, value_a)` and `csr_write(961, value_b)`.

But yeah, I think your suggestion of making the function itself as macros might be better!

2024-07-25 11:32 UTC, rgantonio commented
@IveanEx I think I am convinced @JosseVanDelm's suggestion might be better. Such that you make macros for the function that sets the value immediately. Like how they made the `write_csr`.

```c
#define write_csr(reg, val) ({ \
  asm volatile ("csrw " #reg ", %0" :: "rK"(val)); })
```

2024-07-25 11:42 UTC, IveanEx commented
> > I don't understand however, why we would need to dynamically offset the address?
> 
> Aha! I see the confusion, I think the "dynamically offsetting the address" is the wrong example haha. I think you phrased it better with the "macro-defined addressing".
> 
> Because the current `csr_write` and `csr_read` does not like the:
> 
> ```c
> csr_write(STREAMER_STRIDE_1, value_a);
> csr_write(STREAMER_STRIDE_2, value_b);
> ```
> 
> It requires that we write explicitly the values like `csr_write(960, value_a)` and `csr_write(961, value_b)`.
> 
> But yeah, I think your suggestion of making the function itself as macros might be better!

The dynamic addressing is because the C library I write does not know how many extensions are added in xdma. It is based on the macros it provided. I am finding a point to design the runtime function, so that no matter whatever extensions are provided, there is a standardized way to design it. 

So, I made csr switch case once. Then everyone can use it. If don't do that, the tremendous number of lines of defines is needed, because the number of defines will equals to the number of CSRs at least.

2024-07-25 12:55 UTC, JosseVanDelm commented
@rgantonio @IveanEx's library does use some dynamic offsets, which means that the processor would have to switch between the instructions (and the C compiler would not optimize it - at least in some cases).

I do like the way @IveanEx is writing his library from a C code point of view (nice API and nice error messages), but I'm afraid it comes at quite a huge runtime cost (we are already severely bound by configuration even if we fully flatten all configuration).

Another thing that bothers me is that this is breaking the style of previous C libraries where it is IMHO a bit more flat and easy to see which addresses are setting which values, but I do agree that the current style of the library is also not very easy on the eyes.

For me it would be more useful if we had a static library API (which is generated by the hardware generation scripts).
I'm not sure why we are doing all this setting in possibly-not-optimized C code.

In any way. I'm not going to be the person using these libraries in the end, so actually maybe your call is more important @rgantonio ?

@jorendumoulin what do you think?

2024-07-25 13:45 UTC, rgantonio commented
> In any way. I'm not going to be the person using these libraries in the end, so actually maybe your call is more important @rgantonio ?

I checked what @IveanEx is showing. If we replace @xiaoling-yi 's code with this, it will still optimize it as if it's just inline CSR writes or reads 😄 

I think it's a useful thing and could make things easier. Because at least (1) we have a working CSR function where we can plug variables or macros into it and (2) it encourages making a list of macro naming for the register addresses. Will be much more explicit in knowing what addresses are used. 

At least in my opinion it's useful 😄

2024-07-25 13:47 UTC, rgantonio approved these changes
I will approve since it's a useful thing. If there are no stopping reactions, please feel free to push 😄 

Next step is to convert @xiaoling-yi 's code into this.

2024-07-25 14:38 UTC, JosseVanDelm approved these changes
Okay for me if useful for C testing

2024-07-25 14:39 UTC, merged