Optimize ReaderWriter
KULeuven-MICAS/snax_cluster pull request #345
Opened 2024-09-24 20:56 UTC by IveanEx

This PR optimizes the following in ReaderWriter: 

<s>Replace the **spatialAddrGen** with full adder implementation</s>
Replace all buffers with pipe buffers (except the scalatest one)

2024-09-24 21:18 UTC, IveanEx commented
@rgantonio If you are free, please check if the critical path in control path (valid / ready hand shaking signal) deteriorates with this improvements 😊😊

2024-09-24 21:29 UTC, xiaoling-yi approved these changes

2024-09-25 06:27 UTC, rgantonio requested changes
Setting barrier here first before merge hehe. So that we make sure that the necessary changes are indeed helpful 😄 

Wait a few hours hold on. I will test.

2024-09-25 06:27 UTC, rgantonio commented on hw/chisel/src/test/scala/snax/readerWriter/ReaderTester.scala.bak
Hmm please don't put backups in the repo. Leave them be in the local computers.

2024-09-25 06:30 UTC, rgantonio commented
Also, did you trace or check in Chisel if it fixes the long path?

2024-09-25 17:21 UTC, rgantonio approved these changes
Ok! I can test tomorrow but was this pipe thing from the queue the fix? I can test in synthesis first before plugging in.

2024-09-25 17:31 UTC, merged