Add tracer disable/prefix functionality
KULeuven-MICAS/snax_cluster pull request #399
Opened 2024-11-22 21:06 UTC by JosseVanDelm

This adds two extra options to snitch_cluster, to address #395 

* `--disable-tracing` : turns off tracing for the Verilog simulation
* `--prefix-trace="prefix"`: appends a prefix to the output traces.  If you use this, it will not default to a logs folder anymore, so be sure to include `logs/your_prefix` in the prefix if you want it to end up in a folder.

I'm keeping this as a draft for now because of the following reasons:
* I don't know how to test this for VCS or Questa (@IveanEx @xiaoling-yi ) can you help me with that? Right now it is implemented in a way that is quite likely to break those latter two, although it should be easily fixable with some preprocessor magic (that would make it impossible to use this functionality on VCS or questa though...)
* The argument parser is really janky... It separately parses the options I added, and then passes this on to the simulator. The reason for this is that the rest of the argument parsing is done by `htif.cc` from `riscv-isa-sim/fesvr`... Not sure if we are using any of those arguments right now though...
* @IveanEx has pointed out that there are multiple other places in the systemverilog that write to a separate log file. I would like to detect those and make them happen in a single place... the current way is pretty ugly/impractical...

2024-11-22 21:09 UTC, JosseVanDelm commented on hw/snitch_cluster/src/snitch_cc.sv
> -    automatic string trace_entry;
Main reason for this change is the indentation on all the lines :grimacing:

2024-11-22 21:09 UTC, JosseVanDelm commented on hw/snitch_cluster/src/snitch_cc.sv
> +      $sformat(trace_file, "%s%s", get_trace_file_prefix(), fn);
I wanted to concatenate the strings here in systemverilog, but that made the verilator quite angry, so now I'm using this really dumb sformat

2024-11-22 21:09 UTC, JosseVanDelm commented on target/common/test/verilator_lib.cc
> +svBit enable_tracing() {
I changed this to svBit, because verilator seemed to generate a DPI function that expected that... not sure how else I would've figured out...

2024-11-22 21:09 UTC, JosseVanDelm commented on target/common/test/verilator_lib.cc
> +int get_int_from_env(const char* var_name, int default_value = 0) {
Oops, I should remove this...

2024-11-25 15:07 UTC, JosseVanDelm commented
> @IveanEx has pointed out that there are multiple other places in the systemverilog that write to a separate log file. I would like to detect those and make them happen in a single place... the current way is pretty ugly/impractical...

@IveanEx the only other place I have found this was already behind an `ifndef VERILATOR` inside `hw/future/src/dma/axi_dma_backend.sv`

2024-11-25 22:43 UTC, IveanEx requested changes
This PR breaks the HeMAiA's Verilator simulation flow (**make hemaia_system_vlt** at the root directory). Can you also make a PR to the main branch of HeMAiA to fix it? 

Beside this error, other tests with Questa and VCS can pass without problem.

2024-11-26 13:40 UTC, JosseVanDelm commented on hw/snitch_cluster/src/snitch_cc.sv
> +    `define END_DISABLEBLE_TRACING() end
This has to be removed, it is not used, and it can not be used

2024-11-27 14:53 UTC, IveanEx approved these changes

2024-11-27 14:59 UTC, merged